apiVersion: v1
kind: Namespace
metadata:
  name: gitops-sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-sonarqube-operator-group
  namespace: gitops-sonarqube
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-sonarqube
---
