apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-sonarqube-sonarqube-sonarqube-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-sonarqube
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-sonarqube/sonarqube-sonarqube-sa
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-sonarqube-ocp4.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
