apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-sms-test2
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/sms-test2/namespace
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-sonarqube-ocp4.git
    targetRevision: main
    helm:
      releaseName: sms-test2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
